[build-system]
requires = ["scikit-build-core>=0.11.0"]
build-backend = "scikit_build_core.build"

[project]
name = "pysoltrace"
version = "0.1.0"
description = "Python wrapper for stapi_v2 shared library"
requires-python = ">=3.8"
dependencies = [
    "colorama >= 0.4.6",
    "numpy==2.5.2", 
    "orjson >= 3.10,<4"]

# ADDED: Link your GitHub repository for distribution tools and PyPI
[project.urls]
Homepage = "https://github.com/NLR-SolTrace/SolTrace"
Documentation = "https://github.com/NLR-SolTrace/SolTrace#readme"
Repository = "https://github.com/NLR-SolTrace/SolTrace.git"
"Bug Tracker" = "https://github.com/NLR-SolTrace/SolTrace/issues"

[tool.scikit-build]
cmake.source-dir = "../.."
cmake.build-type = "RelWithDebInfo"

# Hardware flags for users who still need to build from source
cmake.define = { SOLTRACE_BUILD_API = "ON", SOLTRACE_BUILD_GUI = "OFF", SOLTRACE_BUILD_TESTS = "OFF", SOLTRACE_BUILD_EMBREE_SUPPORT = "OFF", SOLTRACE_BUILD_OPTIX_SUPPORT = "ON" }

wheel.packages = ["pysoltrace"]

sdist.include = [
    "../../CMakeLists.txt",
    "../CMakeLists.txt",
    "./**",
    "pysoltrace/**/*.py",
    "../simulation_data/**",
    "../simulation_results/**",
    "../simulation_runner/simulation_runner.hpp",
    "../simulation_runner/native_runner/**",
    "../simulation_runner/embree_runner/**",
    "../simulation_runner/optix_runner/**"
]