# NOTE: the wheel expects the cmake build process to be run before running `py -m build --wheel`
[build-system]
requires = ["hatchling == 1.26"]
build-backend = "hatchling.build"

[project]
name = "pysoltrace"
version = "0.0.1"
description = "Python bindings and utilities for the NLR SolTrace(TM) ray-tracing engine."
readme = "./pysoltrace/README.md"
requires-python = ">=3.10"
dependencies = [
    "colorama >= 0.4.6",
    "numpy >= 2.5.2", 
    "matplotlib >= 3.11.2", 
    "orjson >= 3.10,<4",
    "pandas >= 3.0.5"
]

[project.urls]
Homepage = "https://github.com/NLR-SolTrace/SolTrace"
Documentation = "https://github.com/NLR-SolTrace/SolTrace#readme"
Repository = "https://github.com/NLR-SolTrace/SolTrace.git"
"Bug Tracker" = "https://github.com/NLR-SolTrace/SolTrace/issues"

[tool.hatch.build.targets.sdist]
# exclude development virtual environment and local data files
include = ["pysoltrace"]
exclude = [
    "pysoltrace/.venv",
    "**.csv",
    "**.json",
    "**.pickle",
    # don't need headers or lib because using ctypes
    # "pysoltrace/include",
    # "pysoltrace/lib",
]

[tool.hatch.build.targets.wheel.force-include]
# include build targets
"./pysoltrace/bin" = "pysoltrace/bin"
# include headers for dot_h generation
"./stapi_v2.h" = "pysoltrace/include/stapi_v2.h"
"../simulation_data/solar_position_calculators/solar_position_calculator.hpp" = "pysoltrace/include/solar_position_calculator.hpp"

[tool.hatch.build.targets.wheel.hooks.custom]
path = "pysoltrace/_whl_tag.py"


# [tool.cibuildwheel]
# build = ["cp310-*"]
# 
# [tool.cibuildwheel.linux]
# archs = "x86_64"
# 
# [tool.cibuildwheel.macos]
# archs = "arm64"
# 
# [tool.cibuildwheel.windows]
# archs = "AMD64"