"""Chedder module. Parse a C header (or C++) and exposes dot_h with 
attributes that have the same names as those in the header file. The 
basis of this code was generated by AI, then edited by Nick Edwards.

^-- by Nick | generated docstring --v

Parses a C/C++ header file (plain typedefs, enums, struct/union typedefs --
including nested anonymous members and C++ default member initializers --
and function-pointer typedefs, the kind of thing that sits in an
``extern "C"`` block backing a pybind/ctypes .so or .dll) and exposes the
results as a plain Python class:

    dot_h.st_uint_t           -> ctypes.c_uint    (typedef unsigned int st_uint_t;)
    dot_h.st_return_t         -> ctypes.c_uint    (typedef st_uint_t st_return_t;  -- chain resolved)
    dot_h.st_return_code_t    -> IntEnum           (typedef enum st_return_code : st_return_t {...} st_return_code_t;)
    dot_h.StatusCode          -> IntEnum
    dot_h.empty_args          -> ctypes.Structure   (typedef struct empty_args {} empty_args;)
    dot_h.args_st_sim_setup   -> ctypes.Structure   (fields + resolved C++ default member initializers)
    dot_h.st_api_call_args    -> ctypes.Structure   (contains a nested anonymous union field)
    dot_h.ProgressCallback    -> ctypes.CFUNCTYPE(...)

Plain typedefs are resolved through their full alias chain down to a
concrete ctypes type (``st_return_t`` -> ``st_uint_t`` -> ``unsigned int``
-> ``ctypes.c_uint``) via a recursive, memoized resolver: each alias is
only ever walked once per process, and the result is cached and reused by
every later reference to that name -- whether it's another typedef, an
enum's underlying type, a struct field, or a function-pointer's
return/argument type. This also makes a typedef of one struct to another
(``typedef empty_args args_st_sim_run_v2;``) resolve to the very same
generated class.

Each generated enum class also carries a ``_ctype_`` attribute pointing at
its resolved underlying ctypes type (``ctypes.c_int`` unless the header
gave it an explicit ``: type`` after the enum).

Structs and unions
-------------------
``typedef struct TAG { ... } NAME;`` (and the ``union`` equivalent) become
real ``ctypes.Structure`` / ``ctypes.Union`` subclasses, registered under
both the typedef alias and, if different, the struct's own tag name. Class
shells are created before any fields are resolved, so self- and
cross-referential pointer fields work (a linked-list node's own
``struct node_s* next;``), and so a field can reference another
struct/union defined anywhere else in the same header.

Struct/union bodies are parsed with real brace-depth tracking (not a
regex that assumes no nested braces), so **nested anonymous or named
struct/union members are supported** -- e.g. a tagged-union-style
``payload`` field. A genuinely anonymous nested member (no field name
before the ``;``) has its members hoisted onto the parent via ctypes'
``_anonymous_`` mechanism, mirroring C++ semantics.

**C++ default member initializers** (``uint_fast64_t x = DEFAULT_X;``,
``T* p = nullptr;``, ``size_t n = 0;``) are parsed out of the field
declaration and, where resolvable, applied automatically when you
construct the class with no argument for that field -- ``nullptr``/``NULL``
-> ``None``, ``true``/``false`` -> bool, numeric literals -> themselves,
and any name matching a known enum member -> that member's value.
Anything else (an unresolved ``#define`` macro this module never parsed,
e.g. ``DEFAULT_NUM_THREADS``) is intentionally **not** guessed at -- it's
recorded on the class as ``_unresolved_defaults_`` so you can see it
rather than silently getting a wrong value. Every generated struct/union
also carries ``_field_defaults_`` (the defaults that *were* applied) for
introspection. Classes with no resolvable defaults get no extra
``__init__`` at all, so they cost nothing extra to instantiate.

Array fields and bitfields still aren't parsed -- such a field is skipped
with a warning rather than guessed at, since a wrong guess would silently
misalign every field after it in memory.

Usage
-----
    from chedder import dot_h

    results = [dot_h.StatusCode(code) for code in raw_status_codes]
    perms   = [dot_h.AccessFlags.FLAG_READ | dot_h.AccessFlags.FLAG_WRITE
               for _ in range(n)]

    @dot_h.LogCallback
    def _log(msg: bytes) -> None:
        print(msg.decode())

    buf = dot_h.st_uint_t(5)          # plain typedef used directly as a ctype
    args = dot_h.args_st_sim_setup()  # nullptr/0 defaults applied automatically
    print(args.num_threads)                # 0 -- came from _unresolved_defaults_, see below
    print(args.args_st_sim_setup._unresolved_defaults_)  # {'num_threads': 'DEFAULT_NUM_THREADS'}

Configuration
-------------
Adjust the constants in the "Configuration" section below for your project
(header filename, dev-tree search locations, packaged/production search
locations). All of them can also be overridden per-deployment via the
``PROJECT_HEADER_PATH`` environment variable without touching this file.
"""

from __future__ import annotations

import ctypes, enum, os, re, sys, warnings
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from colorama import just_fix_windows_console, Fore, Back, Style # pyright: ignore[reportMissingModuleSource]
just_fix_windows_console()

__all__ = ["dot_h", "found_in", "locate_header", "reload_header_defs"]

# ---------------------------------------------------------------------------
# Configuration -- edit these for your project
# ---------------------------------------------------------------------------

_HEADER_FILENAME = "stapi_v2.h"

_ENV_HEADER_PATH = "PROJECT_HEADER_PATH"       # explicit full-path override

_STAPI_V2_DIR = Path(__file__).resolve().parent.parent


def _dev_search_paths(filename: str) -> List[Path]:
    """Locations to check when running from a source checkout."""
    return [
        _STAPI_V2_DIR / filename,
        _STAPI_V2_DIR / "include" / filename,
        _STAPI_V2_DIR.parent / "include" / filename,
        _STAPI_V2_DIR.parent / "cpp" / "include" / filename,
        Path.cwd() / "include" / filename,
    ]


def _prod_search_paths(filename: str) -> List[Path]:
    """Locations to check for a pip/whl-installed production deployment."""
    return [
        # Header shipped alongside this module as package data.
        _STAPI_V2_DIR / "_include" / filename,
        # Common "installed into the environment" locations.
        Path(sys.prefix) / "include" / filename,
        Path(sys.prefix) / "share" / "project" / "include" / filename,
    ]


# ---------------------------------------------------------------------------
# Header location
# ---------------------------------------------------------------------------

def locate_header(filename: str = _HEADER_FILENAME) -> Path:
    """Find the header file, dev tree first, then production locations.

    Raises FileNotFoundError with the full search list if nothing matches.
    """
    override = os.environ.get(_ENV_HEADER_PATH)
    candidates: List[Path] = []
    if override:
        candidates.append(Path(override))
    candidates.extend(_dev_search_paths(filename))
    candidates.extend(_prod_search_paths(filename))

    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()

    searched = "\n  ".join(str(c) for c in candidates)
    raise FileNotFoundError(f"Could not locate header '{filename}'. Set {_ENV_HEADER_PATH} to an "
                            f"explicit path, or place the header in one of:\n  {searched}")


# ---------------------------------------------------------------------------
# ctypes type resolution
# ---------------------------------------------------------------------------

_BASE_CTYPES: Dict[str, Optional[type]] = {
    "void": None,
    "char": ctypes.c_char,
    "signed char": ctypes.c_byte,
    "unsigned char": ctypes.c_ubyte,
    "short": ctypes.c_short,
    "short int": ctypes.c_short,
    "unsigned short": ctypes.c_ushort,
    "unsigned short int": ctypes.c_ushort,
    "int": ctypes.c_int,
    "unsigned int": ctypes.c_uint,
    "unsigned": ctypes.c_uint,
    "long": ctypes.c_long,
    "unsigned long": ctypes.c_ulong,
    "long long": ctypes.c_longlong,
    "unsigned long long": ctypes.c_ulonglong,
    "float": ctypes.c_float,
    "double": ctypes.c_double,
    "long double": ctypes.c_longdouble,
    "bool": ctypes.c_bool,
    "_Bool": ctypes.c_bool,
    "size_t": ctypes.c_size_t,
    "ssize_t": ctypes.c_ssize_t,
    "int8_t": ctypes.c_int8,
    "uint8_t": ctypes.c_uint8,
    "int16_t": ctypes.c_int16,
    "uint16_t": ctypes.c_uint16,
    "int32_t": ctypes.c_int32,
    "uint32_t": ctypes.c_uint32,
    "int64_t": ctypes.c_int64,
    "uint64_t": ctypes.c_uint64,
    "int_fast8_t": ctypes.c_int8,
    "uint_fast8_t": ctypes.c_uint8,
    "int_fast16_t": ctypes.c_int64,
    "uint_fast16_t": ctypes.c_uint64,
    "int_fast32_t": ctypes.c_int64,
    "uint_fast32_t": ctypes.c_uint64,
    "int_fast64_t": ctypes.c_int64,
    "uint_fast64_t": ctypes.c_uint64,
    "int_least8_t": ctypes.c_int8,
    "uint_least8_t": ctypes.c_uint8,
    "int_least16_t": ctypes.c_int16,
    "uint_least16_t": ctypes.c_uint16,
    "int_least32_t": ctypes.c_int32,
    "uint_least32_t": ctypes.c_uint32,
    "int_least64_t": ctypes.c_int64,
    "uint_least64_t": ctypes.c_uint64,
    "intmax_t": ctypes.c_int64,
    "uintmax_t": ctypes.c_uint64,
    "intptr_t": ctypes.c_ssize_t,
    "uintptr_t": ctypes.c_size_t,
    "ptrdiff_t": ctypes.c_ssize_t,
    "wchar_t": ctypes.c_wchar,
}

_WS_RE = re.compile(r"\s+")
_QUALIFIER_RE = re.compile(r"\b(const|volatile|struct|union)\b")
_IDENTIFIER_RE = re.compile(r"^[A-Za-z_]\w*$")


def _strip_param_name(arg: str) -> str:
    """Turn 'const char* message' / 'int count' into just the type part,
    while leaving bare types like 'unsigned int' or 'StatusCode' untouched."""
    s = re.sub(r"\*", " * ", arg.strip())
    tokens = s.split()
    if len(tokens) <= 1:
        return arg.strip()
    last = tokens[-1]
    if last == "*" or last in ("const", "volatile"):
        return arg.strip()
    if _IDENTIFIER_RE.match(last) and last not in _BASE_CTYPES:
        tokens = tokens[:-1]
        return " ".join(tokens)
    return arg.strip()


def _split_type_and_name(rest: str) -> Optional[Tuple[str, str]]:
    """Split a declaration's body ('unsigned int st_uint_t') into
    (type_str, alias_name). Returns None if it doesn't look like a valid
    'TYPE NAME' declaration (e.g. malformed input)."""
    s = re.sub(r"\*", " * ", rest.strip())
    tokens = s.split()
    if len(tokens) < 2:
        return None
    name = tokens[-1]
    if not _IDENTIFIER_RE.match(name):
        return None
    type_str = " ".join(tokens[:-1])
    return type_str, name


def _resolve_ctype(type_str: str,
                   typedef_raw: Dict[str, str],
                   enum_ctypes: Dict[str, Any],
                   resolved_cache: Dict[str, Any],
                   _stack: frozenset = frozenset(),
                   struct_ctypes: Optional[Dict[str, Any]] = None):
    """Map a C type string to a ctypes type.

    This is the recursive, memoized alias resolver: when `base` turns out
    to itself be another typedef name, it recurses one link down the chain
    and -- critically -- stores the result in `resolved_cache` before
    returning, so that name never has to be walked again for the rest of
    this build (every later reference, from any other typedef, enum
    underlying-type clause, struct field, or function-pointer signature,
    hits the cache in O(1) instead of re-resolving the chain). `_stack`
    guards against cyclic typedefs (A -> B -> A) turning into infinite
    recursion.

    `struct_ctypes` maps struct/union tag names *and* their typedef alias
    names to the already-created (possibly still field-less) ctypes class,
    so 'struct node_s *' inside another struct's own field list resolves
    correctly -- including the pointer-to-self case a linked-list node
    needs, since the class object exists before its `_fields_` are filled,
    and so a typedef-of-a-struct ('typedef empty_args other_name;')
    resolves to that same generated class.
    """
    struct_ctypes = struct_ctypes or {}
    s = _QUALIFIER_RE.sub("", type_str).strip()
    ptr_count = s.count("*")
    s = _WS_RE.sub(" ", s.replace("*", " ")).strip()
    base = s

    def ptr_wrap(type, count):
        for _ in range(count): type = ctypes.POINTER(type)
        return type 

    if base == "void":
        if ptr_count == 0:
            return None
        return ptr_wrap(ctypes.c_void_p, ptr_count - 1)

    if base == "char" and ptr_count == 1:
        return ctypes.c_char_p

    if base in _stack:
        warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                      f"cyclic typedef chain detected at '{base}'; "
                      f"treating as opaque void*-sized value.",
                      stacklevel=2)
        ctype = ctypes.c_void_p
    elif base in resolved_cache:
        # Memoization hit -- this alias's chain was already walked.
        ctype = resolved_cache[base]
    elif base in enum_ctypes:
        ctype = enum_ctypes[base]
    elif base in struct_ctypes:
        ctype = struct_ctypes[base]
    elif base in typedef_raw:
        ctype = _resolve_ctype(typedef_raw[base], 
                               typedef_raw, 
                               enum_ctypes, 
                               resolved_cache,
                               _stack | {base}, 
                               struct_ctypes)
        resolved_cache[base] = ctype  # memoize before returning
    elif base in _BASE_CTYPES and _BASE_CTYPES[base] is not None:
        ctype = _BASE_CTYPES[base]
    else:
        # Unknown / opaque type (forward-declared struct not defined
        # anywhere in this header, etc.) -- treat as an opaque
        # pointer-sized handle; this keeps parsing resilient instead of
        # failing the whole header on one exotic or externally-defined type.
        if ptr_count == 0:
            warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                          f"unknown non-pointer type '{type_str}', "
                          f"treating as opaque void*-sized value.",
                          stacklevel=2)
        ctype = ctypes.c_void_p
        ptr_count = max(ptr_count - 1, 0)

    return ptr_wrap(ctype, ptr_count)


# ---------------------------------------------------------------------------
# Header text -> intermediate parsed data (plain dicts/tuples)
# ---------------------------------------------------------------------------

_COMMENT_RE = re.compile(r"/\*.*?\*/|//[^\n]*", re.DOTALL)

# #define [NAME] [VALUE]
_DEFINE_RE = re.compile(
    r"#define\s+(?P<name>[0-9A-Za-z_]+\w*)\s+(?:(?P<value>[0-9A-Za-z_.\(\), ]+))",
    re.DOTALL,
)

# typedef enum [class] [TAG] [: UNDERLYING] { BODY } NAME;
# (enum bodies never contain nested braces, so a simple non-nested-brace
# body match is fine here, unlike structs/unions below.)
_ENUM_RE = re.compile(
    r"typedef\s+enum\s*(?:class\s+)?\s*(?:(?P<tag>[A-Za-z_]\w*)\s*)?"
    r"(?::\s*(?P<underlying>[A-Za-z_][\w\s]*?)\s*)?"
    r"\{(?P<body>[^}]*)\}\s*(?P<name>[A-Za-z_]\w*)\s*;",
    re.DOTALL,
)

# typedef RET (*NAME)(ARGS);
_FUNCPTR_RE = re.compile(
    r"typedef\s+(?P<ret>[A-Za-z_][\w\s]*?\**)\s*\(\s*\*\s*(?P<name>[A-Za-z_]\w*)\s*\)"
    r"\s*\(\s*(?P<args>[^)]*)\)\s*;",
)

# typedef TYPE NAME;  (plain aliases, incl. chains like 'typedef st_uint_t st_return_t;'
# and struct-to-struct aliases like 'typedef empty_args args_st_sim_run_v2;')
# Structurally can't match enum/funcptr/struct/union statements since those
# always contain a '{' or '(' before their terminating ';'; 'enum' is
# excluded explicitly too, to skip brace-less forward-declaration forms
# like 'typedef enum Foo Bar;' which conceptually belong with _ENUM_RE.
_TYPEDEF_RE = re.compile(r"typedef\s+(?!enum\b)(?P<rest>[^;{}()\[\]]+?)\s*;")

# Struct/union bodies CAN contain nested braces (nested anonymous unions,
# etc.), which a regex character class can't express with proper nesting.
# So structs/unions are found in two steps: this regex locates just the
# opening "typedef struct|union [TAG] {", then _find_matching_brace() walks
# forward from there to find the real matching close brace by depth.
_STRUCT_HEADER_RE = re.compile(
    r"typedef\s+(?P<kind>struct|union)\s*(?:(?P<tag>[A-Za-z_]\w*)\s*)?\{"
)
# A nested (non-typedef) struct/union member opening, found while walking a
# body: e.g. 'union {' or 'struct node_s {' inside another struct's body.
_COMPOUND_OPEN_RE = re.compile(r"(?P<kind>struct|union)\b\s*(?:[A-Za-z_]\w*)?\s*\{")
# An identifier + ';' immediately following a compound's closing brace,
# e.g. '} payload;' or '} args_st_sim_setup;'.
_NAME_SEMI_RE = re.compile(r"\s*(?P<name>[A-Za-z_]\w*)\s*;")


def _find_matching_brace(text: str, open_idx: int) -> Optional[int]:
    """Given the index of an opening '{' in text, return the index of its
    matching closing '}' by simple depth counting. Returns None if
    unterminated. (Doesn't account for braces inside string/char literals
    -- essentially never seen inside a struct/union body in practice.)"""
    depth = 0
    for i in range(open_idx, len(text)):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i
    return None


def _strip_comments(text: str) -> str:
    return _COMMENT_RE.sub(" ", text)

def _parse_define_value(value: str) -> any:
    expr = value.strip()
    if not len(expr): return None
    try:
        return eval(expr, {"__builtins__": {}}, {})  # noqa: S307
    except Exception:
        warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                      f"could not evaluate #define expression '{expr}'.",
                      stacklevel=2)
        return expr

def _parse_enum_body(body: str) -> Dict[str, int]:
    members: Dict[str, int] = {}
    next_value = 0
    for raw_entry in body.split(","):
        entry = raw_entry.strip()
        if not entry:
            continue
        if "=" in entry:
            name, expr = entry.split("=", 1)
            name = name.strip()
            expr = expr.strip()
            try:
                value = eval(expr, {"__builtins__": {}}, dict(members))  # noqa: S307
            except Exception:
                warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                              f"could not evaluate enum expression "
                              f"'{expr}' for member '{name}'; using auto-increment.",
                              stacklevel=2)
                value = next_value
        else:
            name = entry
            value = next_value
        members[name] = value
        next_value = value + 1
    return members


def _parse_funcptr_args(args: str) -> List[str]:
    args = args.strip()
    if args == "" or args == "void":
        return []
    return [a.strip() for a in args.split(",")]


# ---------------------------------------------------------------------------
# Struct/union field parsing: default member initializers + nested members
# ---------------------------------------------------------------------------

_DEFAULT_LITERAL_NS: Dict[str, Any] = {"nullptr": None, "NULL": None, "true": True, "false": False}


def _eval_default_expr(expr: str, ns: Dict[str, any]) -> Tuple[Any, bool]:
    """Try to evaluate a C++ default member initializer expression
    ('= DEFAULT_NUM_THREADS', '= nullptr', '= 0') as a Python value.

    Only numeric/boolean/nullptr literals and names matching a known enum
    member are supported -- this module doesn't parse '#define' macros, so
    an unresolvable name (like a project-specific macro constant) is
    reported as unresolved rather than guessed at. Returns (value, True) on
    success, (None, False) if the expression couldn't be resolved."""
    try:
        return eval(expr, {"__builtins__": {}}, ns), True # noqa: S307
    except Exception:
        return None, False


def _parse_field_stmt(stmt: str) -> List[Tuple[str, str, Optional[str]]]:
    """Parse one struct/union field statement (no trailing ';') into a list
    of (field_name, type_str, default_expr_or_None). Handles:
      - C++ default member initializers: 'uint_fast64_t n = DEFAULT_N'
      - pointer defaults: 'st_uint_t *seeds = nullptr'
      - comma-separated declarators sharing a type: 'int a, b;'
        (a default on one declarator does not propagate to siblings)
    A comma inside the default expression itself (e.g. a macro call taking
    multiple arguments) isn't handled -- documented limitation, rare in
    practice for a default-member-initializer expression."""
    results: List[Tuple[str, str, Optional[str]]] = []
    parts = [p.strip() for p in stmt.split(",")]
    shared_type: Optional[str] = None
    for idx, part in enumerate(parts):
        default_expr: Optional[str] = None
        if "=" in part:
            decl, default_expr = part.split("=", 1)
            decl, default_expr = decl.strip(), default_expr.strip()
        else:
            decl = part
        if idx == 0:
            split = _split_type_and_name(decl)
            if split is None:
                warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                              f"could not parse struct field '{stmt}'; "
                              f"skipping it (this may misalign the ctypes "
                              f"layout for the rest of the struct).",
                              stacklevel=2)
                return results
            shared_type, name = split
            field_type = shared_type
        else:
            ptr_prefix = ""
            nm = decl
            while nm.startswith("*"):
                ptr_prefix += "*"
                nm = nm[1:].strip()
            if shared_type is None or not _IDENTIFIER_RE.match(nm):
                warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                              f"could not parse struct field "
                              f"'{part}' in '{stmt}'; skipping it.",
                              stacklevel=2)
                continue
            name = nm
            field_type = f"{shared_type} {ptr_prefix}".strip() if ptr_prefix else shared_type
        results.append((name, field_type, default_expr))
    return results


def _parse_compound_body(body: str) -> List[Tuple]:
    """Recursively parse a struct/union body into an ordered member list.
    Each member is one of:
        ('field', name, type_str, default_expr_or_None)
        ('compound', name_or_None, kind, nested_member_list)
    `name` is None for a genuinely anonymous nested struct/union member (no
    field name given before the ';') -- its members get hoisted onto the
    parent via ctypes' `_anonymous_` mechanism when this is built into a
    class, mirroring C++ semantics."""
    members: List[Tuple] = []
    i, n = 0, len(body)
    while i < n:
        while i < n and body[i].isspace():
            i += 1
        if i >= n:
            break
        m = _COMPOUND_OPEN_RE.match(body, i)
        if m:
            kind = m.group("kind")
            open_idx = m.end() - 1
            close_idx = _find_matching_brace(body, open_idx)
            if close_idx is None:
                warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                              f"unterminated nested {kind} body; "
                              f"skipping the rest of this member list.",
                              stacklevel=2)
                break
            inner_body = body[open_idx + 1:close_idx]
            nested_members = _parse_compound_body(inner_body)

            name_match = _NAME_SEMI_RE.match(body, close_idx + 1)
            if name_match:
                members.append(("compound", name_match.group("name"), kind, nested_members))
                i = name_match.end()
            else:
                # No identifier before ';' -> anonymous nested member.
                anon_end = body.find(";", close_idx + 1)
                trailing = body[close_idx + 1:anon_end].strip() if anon_end != -1 else ""
                if trailing:
                    warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                                  f"chedder: could not parse nested {kind} "
                                  f"member declarator '{trailing}'; skipping.",
                                  stacklevel=2)
                else:
                    members.append(("compound", None, kind, nested_members))
                i = (anon_end + 1) if anon_end != -1 else n
            continue

        semi_idx = body.find(";", i)
        if semi_idx == -1:
            break
        stmt = body[i:semi_idx].strip()
        i = semi_idx + 1
        if not stmt:
            continue
        members.extend(
            ("field", fname, ftype, fdefault)
            for fname, ftype, fdefault in _parse_field_stmt(stmt)
        )
    return members


class _ParsedHeader:
    __slots__ = (
        "defines",
        "enums",
        "enum_underlying",
        "funcptrs",
        "typedefs",
        "path",
        "structs"
    )

    def __init__(self,
                 defines: Dict[str, any],
                 enums: Dict[str, Dict[str, int]],
                 enum_underlying: Dict[str, Optional[str]],
                 funcptrs: Dict[str, Tuple[str, List[str]]],
                 typedefs: Dict[str, str],
                 structs: Dict[str, Tuple[Optional[str], str, List[Tuple]]]):
        self.defines = defines
        self.enums = enums
        self.enum_underlying = enum_underlying
        self.funcptrs = funcptrs
        self.typedefs = typedefs
        # name -> (tag, kind, member_list); kind is "struct" or "union";
        # member_list is the recursive structure _parse_compound_body
        # produces (see its docstring).
        self.structs = structs


def _type_label(ctype: Any) -> str:
    """Short human-readable label for a ctypes/enum type -- used when we're
    not expanding it further (base ctypes types have no sub-structure to
    expand)."""
    if ctype is None:
        return "void"
    return getattr(ctype, "__name__", None) or repr(ctype)
 
 
def _describe_member(name: str,
                     value: Any,
                     value_to_name: Dict[int, str],
                     seen: frozenset,
                     indent: str = "",
                     depth: int = 0) -> List[str]:
    """Recursively describe one member. If `value` (after unwrapping any
    pointer layers) is itself present in `value_to_name` -- i.e. it's
    another member of the same HeaderDefs, whether that's a struct/union
    field referencing a named struct/enum, or a typedef aliasing another
    named type directly -- it gets expanded in place (fields, enum
    members, etc.) rather than just named. `seen` breaks a self-reference
    (e.g. a linked-list node's own pointer-to-itself field) by printing a
    plain reference instead of expanding again once a type reappears
    within its own expansion chain."""
    _name = Fore.MAGENTA + name

    if depth > 1: return [f"{indent}{_name}{Style.RESET_ALL}"]
    
    ptr_prefix = ""
    target = value
    while isinstance(target, type) and issubclass(target, ctypes._Pointer):
        ptr_prefix += "*"
        target = getattr(target, "_type_", None)
    suffix = f" {ptr_prefix}" if ptr_prefix else ""
    suffix += Style.RESET_ALL
 
    if isinstance(target, type) and issubclass(target, enum.IntEnum):
        members_desc = ", ".join(f"{m.name}={m.value}" for m in target)
        ctype = getattr(target, "_ctype_", ctypes.c_int)
        return [f"{indent}{_name}{suffix}: {Fore.RED}enum {{{members_desc}}} [ctype={_type_label(ctype)}]"]
 
    if isinstance(target, type) and issubclass(target, (ctypes.Structure, ctypes.Union)):
        kind = f'{Fore.RED}{"union" if issubclass(target, ctypes.Union) else "struct"}'
        tid = id(target)
        if tid in seen:
            canonical = value_to_name.get(tid, target.__name__)
            return [f"{indent}{_name}{suffix}: {kind} {target.__name__}{Style.RESET_ALL} (already expanded above, see '{canonical}')"]
        lines = [f"{indent}{_name}{suffix}: {kind}{Style.RESET_ALL} {{"]
        applied = getattr(target, "_field_defaults_", {})
        unresolved = getattr(target, "_unresolved_defaults_", {})
        anon = set(getattr(target, "_anonymous_", ()))
        for fname, fctype, *_rest in getattr(target, "_fields_", []):
            field_label = f"{fname} (anonymous)" if fname in anon else fname
            if fname in applied:
                field_label += f" = {applied[fname]!r}"
            elif fname in unresolved:
                field_label += f" = {unresolved[fname]} (unresolved)"
            lines.extend(
                _describe_member(field_label,
                                 fctype,
                                 value_to_name,
                                 seen | {tid},
                                 indent + "    ",
                                 depth + 1)
            )
        if not getattr(target, "_fields_", []):
            lines.append(f"{indent}    (empty)")
        lines.append(f"{indent}}}")
        return lines
 
    if isinstance(target, type) and issubclass(target, ctypes._CFuncPtr):
        restype = getattr(target, "_restype_", None)
        argtypes = getattr(target, "_argtypes_", ())
        arg_desc = ", ".join(_type_label(a) for a in argtypes) or "void"
        return [f"{indent}{_name}{Style.RESET_ALL}: {Fore.RED}function pointer ({arg_desc}){Style.RESET_ALL} -> {_type_label(restype)}"]
 
    # Plain ctypes simple type (or unresolved/opaque placeholder). Still
    # note when it's literally the same object as another named member
    # (e.g. two typedefs both aliasing the same base ctype).
    label = f'{Fore.RED}{_type_label(target)}{Style.RESET_ALL}'
    same_as = value_to_name.get(id(target)) if target is not None else None
    if same_as and same_as != name:
        return [f"{indent}{_name}{suffix}: {label}  (same as '{same_as}')"]
    return [f"{indent}{_name}{suffix}: {label}"]
 
 
def found_in(header_defs: type) -> str:
    """Return a flat, human-readable listing of everything found in the
    header and exposed on `header_defs` (typically HeaderDefs) -- plain
    typedefs, enums, structs/unions, and function pointer types together,
    in declaration order, with no typedef/enum/struct grouping.
 
    Introspects `header_defs` itself rather than this module's internal
    parse state, so it also works correctly on a class returned by
    reload_header_defs() rather than only the module-level HeaderDefs.
 
    A member whose value is itself another member of `header_defs` -- a
    typedef that directly aliases another named type
    (`typedef empty_args args_st_sim_run_v2;`), or a struct/union field
    whose type is itself a named struct/union/enum exposed on
    `header_defs`, including through a pointer (`node_t* head;`) -- is
    expanded inline instead of just being named.
 
    Usage:
        from cheader_bindings import HeaderDefs, found_in
        print(found_in(HeaderDefs))
    """
    members = {k: v for k, v in vars(header_defs).items() if not k.startswith("__")}
    value_to_name: Dict[int, str] = {}
    for k, v in members.items():
        value_to_name.setdefault(id(v), k)
 
    lines: List[str] = []
    for name, value in members.items():
        lines.extend(_describe_member(name, value, value_to_name, frozenset()))

    header = f"Parsed header: {locate_header().name}"
    header += f"\n{'-' * len(header)}\n"
    return header + "\n".join(lines)


def _parse_header_text(header_path: Path) -> _ParsedHeader:
    text = header_path.read_bytes().decode("utf-8", errors="replace")
    clean = _strip_comments(text)

    defines: Dict[str, any] = {}
    for match in _DEFINE_RE.finditer(clean):
        name = match.group("name")
        defines[name] = _parse_define_value(match.group("value"))

    enums: Dict[str, Dict[str, int]] = {}
    enum_underlying: Dict[str, Optional[str]] = {}
    for match in _ENUM_RE.finditer(clean):
        name = match.group("name")
        enums[name] = _parse_enum_body(match.group("body"))
        underlying = match.group("underlying")
        enum_underlying[name] = underlying.strip() if underlying else None

    funcptrs: Dict[str, Tuple[str, List[str]]] = {}
    for match in _FUNCPTR_RE.finditer(clean):
        ret = match.group("ret").strip()
        name = match.group("name")
        args = _parse_funcptr_args(match.group("args"))
        funcptrs[name] = (ret, args)

    typedefs: Dict[str, str] = {}
    for match in _TYPEDEF_RE.finditer(clean):
        split = _split_type_and_name(match.group("rest"))
        if split is None:
            continue
        type_str, name = split
        typedefs[name] = type_str

    structs: Dict[str, Tuple[Optional[str], str, List[Tuple]]] = {}
    for match in _STRUCT_HEADER_RE.finditer(clean):
        kind = match.group("kind")
        tag = match.group("tag")
        open_idx = match.end() - 1
        close_idx = _find_matching_brace(clean, open_idx)
        if close_idx is None:
            warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                          f"unterminated {kind} body near offset "
                          f"{match.start()}; skipping.",
                          stacklevel=2)
            continue
        name_match = _NAME_SEMI_RE.match(clean, close_idx + 1)
        if not name_match:
            warnings.warn(f"{Fore.YELLOW}[chedder] - warning{Style.RESET_ALL}: "
                          f"could not find a typedef alias name "
                          f"for the {kind} near offset {match.start()}; skipping.",
                          stacklevel=2)
            continue
        name = name_match.group("name")
        inner_body = clean[open_idx + 1:close_idx]
        members = _parse_compound_body(inner_body)
        structs[name] = (tag, kind, members)

    return _ParsedHeader(defines,
                         enums,
                         enum_underlying,
                         funcptrs,
                         typedefs,
                         structs)


# ---------------------------------------------------------------------------
# Build the Python-facing namespace class from parsed data
# ---------------------------------------------------------------------------

def _make_struct_init(base: type, defaults: Dict[str, Any], field_order: List[str]):
    """Build an __init__ that applies resolved C++ default member
    initializers for any field the caller doesn't explicitly supply
    (positionally or by keyword), then delegates to the real ctypes
    __init__. Only attached to classes with at least one resolved
    default, so structs without defaults pay zero extra overhead per
    instantiation -- important if you're constructing these in bulk
    inside a list comprehension."""
    def __init__(self, *args, **kwargs):
        covered = set(field_order[: len(args)]) | set(kwargs.keys())
        for fname, value in defaults.items():
            if fname not in covered:
                kwargs[fname] = value
        base.__init__(self, *args, **kwargs)
    return __init__


def _build_namespace(parsed: _ParsedHeader, class_name: str = "dot_h") -> type:
    # Flatten every enum member name -> int value up front (independent of
    # when/whether the IntEnum classes themselves get built), so default
    # member initializers that reference an enum constant can resolve.
    enum_value_ns: Dict[str, int] = {}
    for members_dict in parsed.enums.values():
        enum_value_ns.update(members_dict)

    # Step 1: create bare struct/union class shells (no _fields_ yet) before
    # resolving anything else. This is what makes self-referential fields
    # work ('struct node_s* next;' inside node_s itself, for a linked-list
    # node) and lets any struct's field reference any other struct defined
    # anywhere in the header, regardless of declaration order -- ctypes
    # only needs the class object to exist to build a POINTER() to it or
    # use it as a field type, not its _fields_ yet.
    struct_ctypes: Dict[str, Any] = {}
    struct_classes: Dict[str, type] = {}
    for name, (tag, kind, _members) in parsed.structs.items():
        base = ctypes.Union if kind == "union" else ctypes.Structure
        cls = type(name, (base,), {})
        struct_classes[name] = cls
        struct_ctypes[name] = cls
        if tag and tag != name:
            struct_ctypes[tag] = cls

    # Step 2: resolve every plain typedef down to a concrete ctypes type,
    # following alias chains (st_return_t -> st_uint_t -> unsigned int) and
    # struct-to-struct aliases (typedef empty_args args_st_sim_run_v2;).
    # resolved_typedefs doubles as the memoization cache: _resolve_ctype
    # writes every intermediate alias it walks into it, so a chain of
    # depth N is only ever traversed once total across this whole build,
    # no matter how many typedefs/enums/structs/funcptrs reference it.
    resolved_typedefs: Dict[str, Any] = {}
    for name in parsed.typedefs:
        if name not in resolved_typedefs:
            resolved_typedefs[name] = _resolve_ctype(parsed.typedefs[name], 
                                                     parsed.typedefs, 
                                                     {}, 
                                                     resolved_typedefs,
                                                     frozenset({name}), 
                                                     struct_ctypes)

    # Step 3: each enum's underlying ctype: explicit 'enum NAME : UNDERLYING'
    # if the header gave one (itself possibly a typedef chain, resolved via
    # the same memoized cache above), else plain c_int.
    resolved_enum_ctypes: Dict[str, Any] = {}
    for name, underlying_str in parsed.enum_underlying.items():
        if underlying_str:
            resolved_enum_ctypes[name] = _resolve_ctype(underlying_str, 
                                                        parsed.typedefs, 
                                                        {}, 
                                                        resolved_typedefs,
                                                        frozenset(), 
                                                        struct_ctypes)
        else:
            resolved_enum_ctypes[name] = ctypes.c_int

    # Step 4: now that typedefs, enums, and every struct/union name are
    # resolvable, recursively build each struct/union's fields (including
    # nested anonymous/named struct or union members) and apply any
    # resolvable default member initializers.
    def build_fields(owner_name: str, members: List[Tuple]):
        """Returns (ctypes_fields, applied_defaults, unresolved_defaults,
        anonymous_field_names) for one struct/union's member list,
        recursing into nested compound members as needed."""
        ctypes_fields: List[Tuple[str, Any]] = []
        applied_defaults: Dict[str, Any] = {}
        unresolved_defaults: Dict[str, str] = {}
        anon_names: List[str] = []

        default_expr_ns = {**_DEFAULT_LITERAL_NS, **enum_value_ns,  **parsed.defines}

        for idx, member in enumerate(members):
            if member[0] == "field":
                _, fname, type_str, default_expr = member
                field_ctype = _resolve_ctype(type_str,
                                             parsed.typedefs,
                                             resolved_enum_ctypes,
                                             resolved_typedefs,
                                             frozenset(),
                                             struct_ctypes)
                ctypes_fields.append((fname, field_ctype if field_ctype is not None else ctypes.c_void_p))
                if default_expr is not None:
                    value, ok = _eval_default_expr(default_expr, default_expr_ns)
                    if ok:
                        applied_defaults[fname] = value
                    else:
                        unresolved_defaults[fname] = default_expr
            else:  # "compound" -- nested struct/union member
                _, cname, kind, nested_members = member
                anonymous = cname is None
                field_name = cname or f"_anon_{idx}"
                nested_base = ctypes.Union if kind == "union" else ctypes.Structure
                nested_owner = f"{owner_name}__{field_name}"
                nested_cls = type(nested_owner, (nested_base,), {})
                (nested_fields, nested_applied, nested_unresolved,
                 nested_anon) = build_fields(nested_owner, nested_members)
                if nested_anon:
                    nested_cls._anonymous_ = tuple(nested_anon)
                nested_cls._fields_ = nested_fields
                nested_cls._field_defaults_ = nested_applied
                nested_cls._unresolved_defaults_ = nested_unresolved
                if nested_applied:
                    nested_cls.__init__ = _make_struct_init(nested_base,
                                                            nested_applied, 
                                                            [f[0] for f in nested_fields])
                ctypes_fields.append((field_name, nested_cls))
                if anonymous:
                    anon_names.append(field_name)

        return ctypes_fields, applied_defaults, unresolved_defaults, anon_names

    for name, (_tag, kind, members) in parsed.structs.items():
        fields, applied, unresolved, anon = build_fields(name, members)
        cls = struct_classes[name]
        if anon:
            cls._anonymous_ = tuple(anon)
        cls._fields_ = fields
        cls._field_defaults_ = applied
        cls._unresolved_defaults_ = unresolved
        if applied:
            base = ctypes.Union if kind == "union" else ctypes.Structure
            cls.__init__ = _make_struct_init(base,
                                             applied,
                                             [f[0] for f in fields])

    enum_classes: Dict[str, type] = {}
    for name, members in parsed.enums.items():
        enum_cls = enum.IntEnum(name, members)
        enum_cls._ctype_ = resolved_enum_ctypes[name]  # type: ignore[attr-defined]
        enum_classes[name] = enum_cls

    funcptr_types: Dict[str, type] = {}
    for name, (ret_str, arg_strs) in parsed.funcptrs.items():
        ret_ctype = (
            _resolve_ctype(ret_str,
                           parsed.typedefs,
                           resolved_enum_ctypes,
                           resolved_typedefs,
                           frozenset(), 
                           struct_ctypes)
            if ret_str and ret_str != "void"
            else None
        )
        arg_ctypes = [
            _resolve_ctype(_strip_param_name(a),
                           parsed.typedefs,
                           resolved_enum_ctypes,
                           resolved_typedefs,
                           frozenset(),
                           struct_ctypes)
            for a in arg_strs
        ]
        funcptr_types[name] = ctypes.CFUNCTYPE(ret_ctype, *arg_ctypes)

    namespace = {
        'DEFINES': [*parsed.defines.keys()],
        'TYPEDEFS': [*resolved_typedefs.keys()],
        'STRUCS': [*struct_classes.keys()],
        'ENUMS': [*enum_classes.keys()],
        'FUNCPTRS': [*funcptr_types.keys()],
        **parsed.defines,
        **resolved_typedefs,
        **struct_classes,
        **enum_classes,
        **funcptr_types,
        "__slots__": ()
    }
    return type(class_name, (object,), namespace)

def reload_header_defs(header_filename: str = _HEADER_FILENAME) -> type:
    """Re-locate and re-parse the header. Rebinds the module-level
    dot_h to the freshly built class and returns it -- useful for
    development iteration when the header changes between calls within
    the same process; normal usage should just import dot_h."""
    header_path = locate_header(header_filename)
    parsed = _parse_header_text(header_path)
    global dot_h
    dot_h = _build_namespace(parsed)
    return dot_h


# ---------------------------------------------------------------------------
# Module-level execution: this block runs exactly once per process, the
# first time this module is imported (Python caches modules in sys.modules
# for every import after that).
# ---------------------------------------------------------------------------

_header_path = locate_header()
_parsed = _parse_header_text(_header_path)
dot_h = _build_namespace(_parsed)

if __name__ == "__main__":
    print(found_in(dot_h))
